---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: almalinux-8
    image: dokken/almalinux-8
    pre_build_image: true
    privileged: true
    cgroup_parent: docker.slice
    command: /lib/systemd/systemd
  - name: centos-7
    image: dokken/centos-7
    pre_build_image: true
    privileged: true
    cgroup_parent: docker.slice
    command: /usr/lib/systemd/systemd
  - name: centos-stream-8
    image: dokken/centos-stream-8
    pre_build_image: true
    privileged: true
    cgroup_parent: docker.slice
    command: /lib/systemd/systemd
  - name: debian-9
    image: dokken/debian-9
    pre_build_image: true
    privileged: true
    cgroup_parent: docker.slice
    command: /lib/systemd/systemd
  - name: debian-10
    image: dokken/debian-10
    pre_build_image: true
    privileged: true
    cgroup_parent: docker.slice
    command: /lib/systemd/systemd
  - name: debian-11
    image: dokken/debian-11
    pre_build_image: true
    privileged: true
    cgroup_parent: docker.slice
    command: /lib/systemd/systemd
  - name: fedora-30
    image: dokken/fedora-30
    pre_build_image: true
    privileged: true
    cgroup_parent: docker.slice
    command: /lib/systemd/systemd
  - name: ubuntu-18.04
    image: dokken/ubuntu-18.04
    pre_build_image: true
    privileged: true
    cgroup_parent: docker.slice
    command: /lib/systemd/systemd
verifier:
  name: testinfra
